---
title: "Canvas_Registrar_Grades"
author: "Linli Zhou"
date: '2022-06-28'
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r method, include=FALSE}
#goal: compare canvas and registar grades column
#step 1: convert both numeric 0-100 (canvas) and letter grade (registar) into 4.0 scale grades
#step 2: create a unique identifier column by combining people id and course id in both data files
#step 3: mutate registar's grade into canvas data for each row (based on unique identifier)
#step 4: mutate difference (canvas-registar grade) column
##calculate the average difference between registar column with canvas column, 
##group the difference into significant vs nonsignificant vs exact match groups
##filter by course etc.
```


```{r load data, include=FALSE}
# set up working directory
#getwd()
#setwd("S:/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data")
#S:\IR\Data and Analyses\Ad Hoc Projects\2021-2022\Canvas Grades_2022\raw data
#list.files()

# set up: load data files
library(readr) #for read_csv
#read on windows path name is different
#canvas21f<-read_csv("S:/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/1.grade_export_2021FallMain.csv")

#read on mac
canvas21f<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/1.grade_export_2021FallMain.csv")
#read canvas data, read_csv read as a tibble ; read.csv as a regular data frame
canvas21f1<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/3.grade_export_2021Fall1.csv")
canvas21f2<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/4.grade_export_2021Fall2.csv")
canvas21s<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/2.grade_export_2022SpringMain.csv")
canvas21s1<-read.csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/grade_export_Spring1_2022.csv")
canvas21s2<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/grade_export_Spring2_2022.csv" )
canvas21sm<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/grade_export_SummerMain_2021.csv")
canvas21sm1<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/grade_export_Summer1_2021.csv")
canvas21sm2<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/grade_export_Summer2_2021.csv")

#check all names are the same before append
names(canvas21f)
names(canvas21f1)
names(canvas21f2)
names(canvas21s)
names(canvas21s1)
names(canvas21s2)
names(canvas21sm)
names(canvas21sm1)
names(canvas21sm2)

# fix names of canvas21s1 to have the names with others
names(canvas21s1) <- gsub("\\."," ",names(canvas21s1))
names(canvas21s1)

#append/stacking
library(dplyr)#for bind_rows function
canvas21<- bind_rows(canvas21f,canvas21f1,canvas21f2,canvas21s,canvas21s1,canvas21s2,canvas21sm,canvas21sm1,canvas21sm2)#append/stacking data 
glimpse(canvas21)#check rows appended and columns remain the same
rm(canvas21f,canvas21f1,canvas21f2,canvas21s,canvas21s1,canvas21s2,canvas21sm,canvas21sm1,canvas21sm2)

#read registar data
library(readxl) #for read_excel
registrar21<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/raw data/2021-2022all.Student Info by Course and Fiscal Year.xlsx", skip=1)
#skipped the first row because real column name starts from the second row

#set up: view data
library(dplyr) #for glimpse function
glimpse(canvas21)
glimpse(registrar21)

#save merged canvas data and registrar data
library(writexl)
write_xlsx(canvas21,"/Users/linlizhou/Documents/LASELL/data/progameval/canvas.raw.20-21.csv")
write_xlsx(registrar21,"/Users/linlizhou/Documents/LASELL/data/progameval/registrar20-21.xlsx")
```

```{r explore outliers}
canvas21%>%filter(`current score`>100)%>%group_by(course)%>%summarise(count=n())%>%arrange(desc(count))

```


```{r convert grades, include=FALSE}
#step 1: convert both numeric 0-100 (canvas) and letter grade (registar) into 4.0 scale grades
str(canvas21$`current score`) #investigate the grades
library(tidyverse) #for pipes
canvas21<- canvas21 %>% 
  mutate(canvasgpa=case_when(# use case_when to mutate new var canvasgpa
    `current score`<=110 &`current score`>=93 ~ 4,
    `current score`<93 & `current score`>=90 ~ 3.7,
    `current score`<90 & `current score`>=87 ~ 3.3,
    `current score`<87 & `current score`>=83 ~ 3,
    `current score`<83 & `current score`>=80 ~ 2.7,
    `current score`<80 & `current score`>=77 ~ 2.3,
    `current score`<77 & `current score`>=73 ~ 2,
    `current score`<73 & `current score`>=70 ~ 1.7,
    `current score`<70 & `current score`>=67 ~ 1.3,
    `current score`<67 & `current score`>=63 ~ 1,
    `current score`<63 & `current score`>59 ~ 0.7,
    `current score`<=59 &`current score`>=0 ~ 0
  ))
glimpse(canvas21)#check
canvas21%>% group_by(canvasgpa)%>%count()#count each category

str(registrar21$`Final Grade`) #investigate grades
registrar21%>% group_by(`Final Grade`)%>%count()#count each category
registrar21<- registrar21 %>% # use case_when to mutate new var registrargpa
  mutate(registrargpa=case_when(
    `Final Grade`=="A" ~ 4,
    `Final Grade`=="A-" ~ 3.7,
    `Final Grade`=="B+" ~ 3.3,
    `Final Grade`=="B" ~ 3,
    `Final Grade`=="B-" ~ 2.7,
    `Final Grade`=="C+" ~ 2.3,
    `Final Grade`=="C" ~ 2,
    `Final Grade`=="C-" ~ 1.7,
    `Final Grade`=="D+" ~ 1.3,
    `Final Grade`=="D" ~ 1,
    `Final Grade`=="D-" ~ 0.7,
    `Final Grade`=="F" ~ 0
  ))
glimpse(registrar21)#check
registrar21%>% group_by(registrargpa)%>%count()#count each category
```


```{r unique identifier, include=FALSE}
#step 2: create a unique identifier column by combining people id and course id in both data files
str(registrar21$`People Code ID`)#check people id in registar data
str(canvas21$`student sis`)#check people id in canvas data
str(registrar21$`Course ID`)#check course id in registar data
str(canvas21$`course`)#check course id in canvas data

#convert course id in canvas to match the format of course id in registar data
str(unlist(lapply(strsplit(canvas21$course, "[.]"), '[[',1))) 
#use [.] instead of . b/c the latter is a reg express
#use strsplit to split the strings into list of elements within the original list
# use lapply to select the first element in the nested list
#use unlist to convert a list into vector

#mutate the new formatted course id in canvas data
canvas21<- canvas21 %>% mutate(cvcrsid=unlist(lapply(strsplit(canvas21$course, "[.]"), '[[',1)))
glimpse(canvas21) #check

#concatenate peopleid+courseid together in registrar data
registrar21<- registrar21 %>% mutate(
  matchid=paste(registrar21$`People Code ID`,registrar21$`Course ID`,sep="")
)
glimpse(registrar21) #check

#concatenate peopleid+courseid together in canvas data
canvas21<- canvas21 %>% mutate(
  matchid=paste(canvas21$`student sis`,canvas21$`cvcrsid`,sep="")
)
glimpse(canvas21) #check
```


```{r merge datasets, include=FALSE}
#step 3: merge registar's grade into canvas data for each row (based on unique identifier)
mg21f<-inner_join(canvas21, registrar21, by="matchid")
glimpse(mg21f)

mg21f<-mg21f%>%select(matchid, canvasgpa, registrargpa,`Course Department`, `Academic Year`,`Academic Term`,`Academic Session`,`Course ID`,`Course Name`,`Course Credits`,`Add Drop`,`Gender`,`Ethnicity`,`Program`,`Major`, `Semester GPA`,`Cumulative GPA`)
glimpse(mg21f)
```


```{r export clean dataset, include=FALSE}
#step 4 option 1: export cleaned data and do analyze/viz in excel
library('writexl')
write_xlsx(mg21f,"S:/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022/gradalign_working.xlsx")
list.files("S:/IR/Data and Analyses/Ad Hoc Projects/2021-2022/Canvas Grades_2022")

```

```{r analysis}
#step 4 option 2: analyze directly in R

#calculate difference (canvas-registar grade) column
##
##
```

