---
title: "Infographic"
author: "Linli Zhou"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Load some R packages: 
library(tidyverse)
library(waffle) # square pie or matrix charts
library(patchwork)
library(lubridate)
library(extrafont)
library(ggtext)
library(Cairo)
library(grid)
library(ggplot2)
library(ggedit)
library(magick)
library(readxl)

# Set theme font for all plots: 
my_font <- "Roboto Condensed"
theme<-theme(plot.title = element_text(color = "#292929"),
        plot.subtitle = element_text(color = "#292929"),
        plot.caption = element_text(face = "bold.italic", family = my_font),
        strip.text.x = element_text(face = "bold", color = "#292929"),
        
        plot.background = element_rect("#EBEBEB"),
        panel.background = element_blank(),
        strip.background = element_blank(),
        panel.spacing = unit(2, "lines"))
#data
alum<-read_excel("/Users/linlizhou/Documents/LASELL/data/alumni/alum.xlsx")

logo<-image_read("/Users/linlizhou/Documents/LASELL/data/LU_Institutional Research_lockup-01.png")
```

```{r plots, include=FALSE}
p1<-alum%>%group_by(Employment)%>%summarise(cnt=n())%>%mutate(prt=formattable::percent(cnt/sum(cnt),digits = 0))%>%ggplot(aes(x=Employment,y=prt))+geom_bar(stat = "identity")+labs(title="p1")

p2<-alum%>%group_by(`Full/Part Time`)%>%summarise(cnt=n())%>%mutate(prt=formattable::percent(cnt/sum(cnt),digits = 0))%>%ggplot(aes(x=`Full/Part Time`,y=prt))+geom_bar(stat = "identity")+labs(title="p2")

p3<-alum%>%group_by(Income)%>%summarise(cnt=n())%>%mutate(prt=formattable::percent(cnt/sum(cnt),digits = 0))%>%ggplot(aes(x=Income,y=prt))+geom_bar(stat = "identity")+labs(title="p3")

p4<-alum%>%group_by(`Further Education`)%>%summarise(cnt=n())%>%mutate(prt=formattable::percent(cnt/sum(cnt),digits = 0))%>%ggplot(aes(x=`Further Education`,y=prt))+geom_bar(stat = "identity")+labs(title="p4")

p5<-alum%>%group_by(Interest)%>%summarise(cnt=n())%>%mutate(prt=formattable::percent(cnt/sum(cnt),digits = 0))%>%ggplot(aes(x=Interest,y=prt))+geom_bar(stat = "identity")+labs(title="p5")
```

```{r}
layout(matrix(c(1,2,3,4),byrow=TRUE,nrow=2,ncol=2))


nf<-layout( mat=matrix(c(1,2), ncol=2) )
layout.show(nf)
p1
p2


#def.par <- par(no.readonly = TRUE) # save default, for resetting...
#par(def.par)  #- reset to default

```


```{r}
pdf("/Users/linlizhou/Downloads/Rinfographic.pdf", width = 10, height = 20)

grid.newpage()#Start by creating new grid plot
pushViewport(viewport(layout = grid.layout(4, 3,widths = c(),heights = c(3,5,5,5),c("cm","cm","cm","cm"))))#a matrix plot with (m rows, n columns)
grid.rect(gp = gpar(lty = "blank",fill="white"))#background
grid.raster(logo,
            x = unit(.5, "npc"), y = unit(.95, "npc"))
grid.text("survey name",
          gp=gpar(fontsize=25, col="black"), 
          x = unit(.5, "npc"), y = unit(.9, "npc"))
grid.text("#responses collected during #~#",
          gp=gpar(fontsize=20, col="grey30"), 
          x = unit(.5, "npc"), y = unit(.88, "npc"))
#paste plot to (row,column)
print(p1, vp = vplayout(2, 1))
print(p2, vp = vplayout(2, 2))
print(p5, vp = vplayout(2, 3))
print(p3, vp = vplayout(3, 1:3))
print(p4, vp = vplayout(4, 1:3))

dev.off()
```
