---
title: "Clearinghouse"
author: "Linli Zhou"
date: "2022-08-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(writexl)
```

```{r read data files and explore data sources}
#NSC needs First Name, Last Name, DOB, Search date, school code, PCID

# Graduates Population: IR  Final List of Graduates By Date Range-Including Certs contains all graduates data in one click
grad13.22<-read.csv("/Users/linlizhou/Downloads/Final List of Graduates By Date Range-Including Certs.csv")
#need to find date of birth info
dtm<-read_excel("/Volumes/lasellshare-1/Faculty_Staff_Shares$/IR/Datamart Files/DataMart To Date/Final Datamart up to Date 07202022.xlsx")

#check if all graduates are in the dtm file
sum((grad13.22$textbox41 %in% dtm$PC_ID)==FALSE)#2525 not found
grad13.22[(grad13.22$textbox41 %in% dtm$PC_ID)==FALSE,]%>%group_by(program1)%>%count()#Missings are all GRAD and 22 PS

ug13.22<-grad13.22[(grad13.22$textbox41 %in% dtm$PC_ID)==TRUE,]#only keep those that can find a match
```


```{r select and reformat dmt}
#select useful cols from datamart
dtm_s<-dtm%>%select(PC_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,SUFFIX,BIRTHDATE)#subset of dtm -- created a new df name, since the original file takes too long to read -- better to keep it in the enviornment rather than reread it each time wanting to change the subset

###reofrmat the data
#extract first letter of middle initial
dtm_s$MIDDLE_NAME<-substr(dtm_s$MIDDLE_NAME,1,1)#start and stop on the first character of the string -- extract first letter of initials
#replace na with empty string
dtm_s$MIDDLE_NAME<-dtm_s$MIDDLE_NAME%>%replace(is.na(dtm_s$MIDDLE_NAME),"")#remove NA values as blank

#replace na with empty string
dtm_s$SUFFIX<-dtm_s$SUFFIX%>%replace(is.na(dtm_s$SUFFIX),"")#remove NA values as blank

#reformat birthdate
dtm_s$BIRTHDATE<-as.character(dtm_s$BIRTHDATE)
#replace-with emplty string
dtm_s$BIRTHDATE<-gsub("-","",dtm_s$BIRTHDATE)
```


```{r inital nsc: match useful col}
#match dtm cols with graduates population and save it as an initial nsc df
nsc<-left_join(ug13.22,dtm_s,by=c("textbox41"="PC_ID"))%>%unique()
```


```{r prep/mutate and lay out col needed}
names(nsc)
#colC:firstname
#colD:middleinitial
#colE:lastname
#colF:suffix
#colG:dateofbirth
#colL:pcid

#student informtion: from row 2- nrow
nsc<-nsc%>%mutate(colA="D1",#meaning "data rows"
                  colB="",#omit ssn
                  colH=as.character("20130101"),#search date (ealiest possible date in expected result)
                  colI="",#leave blank
                  colJ=as.character("002158"),#schoolcode, must be as character, unless the 00 will be 0
                  colK=as.character("00")#branch code, must be as character, unless the 00 will be omitted
                  )
```


```{r select col - student info/detail rows/section completed}
nsc<-nsc%>%select(colA,colB,FIRST_NAME,MIDDLE_NAME,LAST_NAME,SUFFIX,BIRTHDATE,colH,colI,colJ,colK,textbox41)%>%unique()
#the student information section (data section) completed
```

```{r header row}
#rename the current names and turn it into the nsc guideline's header row
names(nsc)<-c(
  "H1",#colA start of the header row
  "002158",#colB school code
  "00",#colC branch code
  "Lasell University",#colD school name
  "20220820",#colE file creation date
  "SE",#colF query option, "Subsequent enrollment", prior attendance, declined admissions, longitudinal cohort
  "I",#colG institution first initial capital
  "",#colH
  "",#colI
  "",#colJ
  "",#colK
  ""#colL
)
```

```{r trailer row}
#check if header is the first row, or not counted in row
head(nsc)#header is not count as a row, then the ultimate row needs to add 1 for the header row

#col
ncol(nsc)#12 cols -- needs 12 col to append rows

#make the trailer row of nsc file
nsc_final<-nsc%>% rbind(c("T1",#indicate trailer row
                        nrow(nsc)+2,#row count + header row + the row itself
                        "", #add the rest of col to make it 12 cols (col values are empty values)
                        "", #4th
                        "", #5th
                        "", #6th
                        "", #7th birth date - but is character class via as.character and gsub the "-"
                        "", #8th search date - but is character class via as.character when creating it
                        "", #9th
                        "", #10th
                        "", #11th
                        ""#12th
                        ))
#I did not use nsc[nrow(nsc) + 1,] = c(...) becasue that would add one row each time I run it
#new variable nsc_final won't be loop in the nsc+1; all that's affect will be nsc itself -- static predefined df; and new version is not called nsc but nsc_final so nsc won't be keep adding a row (only the preset nsc back in the code again) when codes are run

tail(nsc_final,1) # n(student)=3292 + header row + added trailer row = 3294
```

```{r output nsc_final}
#save file as tab delimited file
#name the file with school code
write.table(nsc_final, #df to be saved
            "/Users/linlizhou/Documents/LASELL/data/completion/NSC002158.txt", 
            #name of result file must be .txt for tab separated/delimited text file 
            sep = "\t", #for tab-separated value
            quote = FALSE, #without quotes
            col.names = TRUE, #print out headers as first row
            row.names = FALSE #so that the row numbers are not printed out
            )
```



```{r archive codes}
#add a col called T1
#nsc<-nsc%>%mutate(T1="D1",#Add the first col A header "T1" and its value "D1" indicating rows of data 
                 # `002158`="",#Add the second col B header school code and leave blank (ssn) for values in rows
               #   `I`=BIRTHDATE,#Add col G header institution initial capital I; colG values are birthdate
                #  ``=as.Date("20130101",format="%Y%m%d")#col H is blank header, with values of search date (earlist possible date that result may appear)
              #    )
#rename the other cols
#nsc%>%rename(`00`=FIRST_NAME,#the third col C header is the branch code, while the row values are first names in col c (3rd col)
            # `Lasell University`=MIDDLE_NAME,#Add the fourth col (col D) with school name, and extract the first letter for middle initials
             #`20200820`=LAST_NAME,#cold E header: file creation date, colE values: last name as the values
             #SE=SUFFIX,#col F header is query option, SE is subsequent enrollment; col F values are suffix
             #)

```

