
```{r libraries}
source("/Users/linlizhou/Documents/Rprojects/IR-Projects/theme_source.R")
```

```{r read_pdf}
#define a regex for any character or digit group
reg <- "([^A-Za-z\\d#@']|'(?![A-Za-z\\d#@]))" 

#define a function to break texts into single word per line
text_prepr <- function(f){
  df <- pdf_text(f) %>% as.tibble()%>% rename(ptext = value) %>%#one pdf page per row (value col)
    unnest_tokens(btext, ptext, #break ptext into btext
    token = "regex", pattern = reg)#unit of breaking texts
  return(df)}#btext is one word (one per row in btext col)
```

```{r fnames}
#2.prep file names for systematic reading
path<-"/Users/linlizhou/Documents/Rprojects/RCodes4DataAnalytics/Data_Science_Ed/AIR-Forum_TextAnalysis/data"
fnames<-list.files(path, pattern="*.pdf", full.names = TRUE)
```

```{r dta}
#3.create dta
dta<-data.frame()#initialize
for (f in fnames) {#for each file
year<-str_extract(f,"(\\d){4}")#extract 4digit group in file name
temp<-text_prepr(f)%>%mutate(year)#break file and add year
dta<-rbind(dta, temp);rm(temp)}#bind by row
```

```{r tbl}
# filter for keywords and count by word and year
tbl<-dta %>% mutate(word = tolower(word)) %>% 
  filter(word %in% c("excel", "sas", "spss","r","python")) %>% 
  group_by(year,word)%>%summarise(cnt=n())%>%
  mutate(prt=cnt/sum(cnt))
```

```{r viz_stackbar}
tbl%>%ggplot(aes(x = year, y = prt, fill=word))+
  geom_bar(stat="identity",position = position_stack(),width=0.9)+
  scale_fill_manual(values = c("darkgrey","lightblue","yellow","orange","lightgreen","lightgrey","#69b3e7"),guide = guide_legend(reverse = TRUE))
```

```{r viz_line}
tbl%>%ggplot(aes(x = year, y = prt, 
                 color = word, group = word))+
  geom_line()+
  scale_color_manual(values = c("black","pink","orange","yellow","darkgrey"),guide = guide_legend(reverse = TRUE))+
  geom_point(aes(x = year, y = prt, color = word), size = 1)+
  scale_y_continuous(breaks = seq(0, 1, by = 0.2) ,labels=scales::percent_format(accuracy = 1))+#present y axis label as percentage
  labs(x = "AIR Forum Year", y = "Percentage of Mentions",
      title = "Data Analysis Software Mentioned in AIR Forum Program Book (2010-2022)")+ 
    theme_lz()+
  theme(axis.text.x = element_text(),
        axis.text.y = element_text(),
        legend.margin=margin(t=0),
        legend.title = element_blank(),
        legend.text = element_text(size=9),
        panel.grid.major.y = element_line())
```

```{r}
scale_x_continuous(limits = c(2010,2022), breaks=(seq(2010,2022, 1)))+
  geom_text_repel(aes(label=word,size=3, hjust=1,vjust=0)+
```
