---
title: "IPEDScomplete-cached"
author: "Linli Zhou"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)#echo is codes
```

```{r load r package}
library(readxl)
library(tidyverse)
#library(dplyr)
#library(plyr)#for join_all
#detach("package:plyr", unload=TRUE)
library(writexl)#write_xlsx
library(lubridate)
library(stringr)
```

```{r CACHED select var from annual, cache=TRUE}
#####direclty use Graduation Term Snapshot which contains all cols (PCID,level,degree,major,gradd,race,gender) I wanted####
#read  data (from report manager-IR-Graduation Term Snapshot)
#AY21-22
#grad21sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/21sum.csv")
#grad21f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/21f.csv")
#grad22spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/22spr.csv")
#AY20-21
#grad20sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/20sum.csv")
#grad20f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/20f.csv")
#grad21spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/21spr.csv")
#AY19-20
#grad19sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/19sum.csv")
#grad19f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/19f.csv")
#grad20spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/20spr.csv")
#AY-18-19
#grad18sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/18sum.csv")
#grad18f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/18f.csv")
#grad19spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/19spr.csv")
#AY17-18
#grad17sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/17sum.csv")
#grad17f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/17f.csv")
#grad18spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/18spr.csv")
#AY16-17
#grad16sum<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/16sum.csv")
#grad16f<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/16f.csv")
#grad17spr<-read.csv("/Users/linlizhou/Documents/LASELL/data/completion/RptMgr.grdbydg/17spr.csv")
#merge
#ipeds.complete16_crt<-
#  join_all(list(grad21sum,grad22spr,grad21f,
#                grad20sum,grad21spr,grad20f,
#                grad19sum,grad20spr,grad19f,
 #               grad18sum,grad19spr,grad18f,
  #              grad17sum,grad18spr,grad17f,
   #             grad16sum,grad17spr,grad16f),
    #       type="full",match="first")%>%
  #select(people_code_id,program,degree,major,graduation_date,Reporting_Ethnicity,gender)%>%
  #dplyr::rename(PCID=people_code_id,level=program,gradd=graduation_date,race=Reporting_Ethnicity)
#remove
#rm(grad21sum,grad22spr,grad21f,
 #  grad20sum,grad21spr,grad20f,
  # grad19f,grad19sum,grad20spr,
   #grad18f,grad18sum,grad19spr,
#   grad17sum,grad18spr,grad17f,
 #  grad16sum,grad17spr,grad16f)

#####reformat date#####
#class(ipeds.complete16_crt$gradd)#it's character
#convert the mdy formated character to date format
#ipeds.complete16_crt$gradd<-mdy_hms(ipeds.complete16_crt$gradd)
#class(ipeds.complete16_crt$gradd)#now it's date

#save merged data
#write_xlsx(ipeds.complete16_crt,"/Users/linlizhou/Documents/LASELL/data/completion/16-current.xlsx")
ipeds.complete16_crt<-read_csv("/Users/linlizhou/Documents/LASELL/data/completion/16-current.xlsx")
```

```{r refining ipeds.compeltes}
#########level: Graduate Students, Undergraduate Students######
ipeds.complete16_crt%>%group_by(level)%>%dplyr::count()
#recode level
ipeds.complete16_crt$level<-ipeds.complete16_crt$level%>%recode(GRAD="Graduate Students",Graduate="Graduate Students",UNDER="Undergraduate Students",Undergraduate="Undergraduate Students")
#remove non gd/ug
ipeds.complete16_crt<-ipeds.complete16_crt%>%filter(level=="Graduate Students" | level== "Undergraduate Students")
#check
ipeds.complete16_crt%>%group_by(level)%>%dplyr::count()#level only contains Graduate Students, Undergraduate Students now

#########degree########
ipeds.complete16_crt%>%group_by(degree)%>%dplyr::count()#20 degrees, seems alright

######major########
list<-ipeds.complete16_crt%>%group_by(major)%>%dplyr::count()

ipeds.complete16_crt$major<-str_trim(ipeds.complete16_crt$major)#remove space at the end of major values
ipeds.complete16_crt$major<-ipeds.complete16_crt$major%>%
  recode(`Athletic Training MSAT`="Athletic Training",
         `Business Administration 2`="Business Administration",
         `Elementary Education MED`="Elementary Education",
         `Hospitality and Event Management`="Hospitality Management",
         `Initial Licensure MED`="Initial Licensure",
         `Initial Licensure MD`="Initial Licensure",
         `SecEduc & Applied Math`="Secondary Education",
         `Elementary Education and Applied Math`="Elementary Education",
         `Secondary Education and Applied Math`="Secondary Education")

####mutate a school col#####
ipeds.complete16_crt<-ipeds.complete16_crt%>%mutate(school=case_when(
  major=="Accounting"~"School of Business",
major=="Applied Forensic Science"~"School of Health Sciences",
major=="Applied Mathematics"~"School of Health Sciences",
major=="Arts Management"~"School of Business",
major=="Athletic Training"~"School of Health Sciences",
major=="Biology"~"School of Health Sciences",
major=="Business Administration"~"School of Business",
major=="Business Management"~"School of Business",
major=="Communication"~"School of Communication & the Arts",
major=="Creative Writing GR"~"School of Communication & the Arts",
major=="Criminal Justice"~"School of Humanities, Education, Justice & Social Sciences",
major=="Curriculum, Leadership & Inclusion"~"School of Humanities, Education, Justice & Social Sciences",
major=="Cybersecurity"~"School of Health Sciences",
major=="Data Analytics"~"School of Health Sciences",
major=="Early Childhood Education"~"School of Humanities, Education, Justice & Social Sciences",
major=="Elementary Education"~"School of Humanities, Education, Justice & Social Sciences",
major=="English"~"School of Humanities, Education, Justice & Social Sciences",
major=="Entrepreneurship"~"School of Business",
major=="Environmental Studies"~"School of Health Sciences",
major=="Event Management"~"School of Business",
major=="Exercise Science"~"School of Health Sciences",
major=="Fashion and Retail Merchandising"~"School of Fashion",
major=="Fashion Communication & Promotion"~"School of Fashion",
major=="Fashion Design and Production"~"School of Fashion",
major=="Finance"~"School of Business",
major=="Fitness Management"~"School of Business",
major=="Global Engagement"~"School of Humanities, Education, Justice & Social Sciences",
major=="Global Studies"~"School of Humanities, Education, Justice & Social Sciences",
major=="Graphic Design"~"School of Communication & the Arts",
major=="Health Communication"~"School of Health Sciences",
major=="Health Science"~"School of Health Sciences",
major=="History"~"School of Humanities, Education, Justice & Social Sciences",
major=="Hospitality Management"~"School of Business",
major=="Human Resources Management"~"School of Business",
major=="Human Services"~"School of Humanities, Education, Justice & Social Sciences",
major=="Humanities"~"School of Humanities, Education, Justice & Social Sciences",
major=="IDS Curriculum & Instruction"~"School of Humanities, Education, Justice & Social Sciences",
major=="IDS Early Childhood Education"~"School of Humanities, Education, Justice & Social Sciences",
major=="IDS Forensic Criminology"~"School of Health Sciences",
major=="IDS Individualized"~"?",
major=="IDS Studio Arts"~"School of Communication & the Arts",
major=="Information Technology"~"School of Health Sciences",
major=="Initial Licensure"~"School of Humanities, Education, Justice & Social Sciences",
major=="Integrated Marketing Communication"~"School of Business",
major=="International Business"~"School of Business",
major=="Law and Public Affairs"~"School of Humanities, Education, Justice & Social Sciences",
major=="Legal Studies"~"School of Humanities, Education, Justice & Social Sciences",
major=="Management"~"School of Business",
major=="Marketing"~"School of Business",
major=="Moderate Disabilities"~"School of Humanities, Education, Justice & Social Sciences",
major=="Non Profit Management"~"School of Business",
major=="Nutrition for Human Performance"~"School of Health Sciences",
major=="Professional Licensure MD"~"School of Humanities, Education, Justice & Social Sciences",
major=="Project Management"~"School of Business",
major=="Psychology"~"School of Humanities, Education, Justice & Social Sciences",
major=="Public Relations MS Concentration"~"School of Communication & the Arts",
major=="Rehabilitation Science"~"School of Health Sciences",
major=="Resort and Casino Management"~"School of Business",
major=="Secondary Education"~"School of Humanities, Education, Justice & Social Sciences",
major=="Secondary Education and English"~"School of Humanities, Education, Justice & Social Sciences",
major=="Secondary Education and History"~"School of Humanities, Education, Justice & Social Sciences",
major=="Sociology"~"School of Humanities, Education, Justice & Social Sciences",
major=="Sport Leadership"~"School of Business",
major=="Sport Management"~"School of Business"
))

########gradd########
ipeds.complete16_crt%>%group_by(gradd)%>%dplyr::count()
ipeds.complete16_crt$gradd<-format(ipeds.complete16_crt$gradd, format = "%Y")#keep year only

######race########
ipeds.complete16_crt%>%group_by(race)%>%dplyr::count()
######gender########
ipeds.complete16_crt%>%group_by(gender)%>%dplyr::count()
ipeds.complete16_crt$gender<-ipeds.complete16_crt$gender%>%recode(
  `F`="Female",
 `M`="Male",
  `U`="Unknown"
)

#save cleaned data
#write_xlsx(ipeds.complete16_crt,"/Users/linlizhou/Documents/LASELL/data/completion/16-current.xlsx")
```



```{r archive codes}
###########################2021 fall ipeds.complete
#check which sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2021IPEDScompletions.xlsx")
#read data
#ipeds.complete21f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2021IPEDScompletions.xlsx",sheet = "Degrees - Combined")
#select useful cols and rename (prep for merge)
#ipeds.complete21f<-ipeds.complete21f%>%select(textbox41,textbox14,DEGREE,major,`Grad Date`)%>%dplyr::rename(PCID=textbox41,level=textbox14,degree=DEGREE,gradd=`Grad Date`)
#check names - prep for merge
#names(ipeds.complete21f)#do not have race and gender in raw data

############################2020 fall ipeds.complete#
#find the right sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2020Merged Completions.xlsx")
#read data
#ipeds.complete20f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2020Merged Completions.xlsx",sheet = "Merged")
#select useful cols and rename (prep for merge)
#ipeds.complete20f<-ipeds.complete20f%>% select(`People Code ID`,Program,Degree,Curriculum,GradDate,Race,Gender) %>% 
 # dplyr::rename(PCID=`People Code ID`, level=Program, degree=Degree, major=Curriculum, gradd=GradDate, race=Race, gender=Gender)
#check names - prep for merge
#names(ipeds.complete20f)#keep a cip description for later use

############################2019 fall ipeds.complete
#find the right sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2019Merged Completions.xlsm")
#read data
#ipeds.complete19f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2019Merged Completions.xlsm",sheet = "AllMerged")
#select useful cols and rename (prep for merge)
#ipeds.complete19f<-ipeds.complete19f%>%select(people_code_id,program,degree,curriculum,graduation_date,Race,gender)%>%dplyr::rename(PCID=people_code_id,level=program,major=curriculum,gradd=graduation_date,race=Race)
#check names - prep for merge
#names(ipeds.complete19f)

############################2018 fall ipeds.complete
#find the right sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2018ipedsFComp_2017grad.clean.xlsx")
#read data
#ipeds.complete18f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2018ipedsFComp_2017grad.clean.xlsx")
#select useful cols and rename (prep for merge)
#ipeds.complete18f<-ipeds.complete18f%>%select(people_code_id,program,degree,curriculum,graduation_date,Race,gender)%>%
#  dplyr::rename(PCID=people_code_id,level=program,major=curriculum,gradd=graduation_date,race=Race)
#check names - prep for merge
#names(ipeds.complete18f)

############################2017 fall ipeds.complete
#find the right sheet to read
#excel_sheets("/Users/linlizhou/Documents/LASELL/data/completion/2017ipedsFComp_2016grad.xlsx")
#read data
#ipeds.complete17f<-read_excel("/Users/linlizhou/Documents/LASELL/data/completion/2017ipedsFComp_2016grad.xlsx",sheet = "Merged_ALL")
#select useful cols and rename (prep for merge)
#ipeds.complete17f<-ipeds.complete17f%>%select(`People Code ID`,Program,Degree,Curriculum,`Graduation Date`,Race,Gender)%>%dplyr::rename(PCID=`People Code ID`,level=Program,degree=Degree,major=Curriculum,gradd=`Graduation Date`,race=Race,gender=Gender)
#check names - prep for merge
#names(ipeds.complete17f)
```

```{r explore merging functions}
#########################explore the different functions using 17-20f data
#rbind needs col of same length
#ncol(ipeds.complete17f)
#ncol(ipeds.complete18f)
#ncol(ipeds.complete19f)
#ncol(ipeds.complete20f)
#rbind
#ipeds.complete<-rbind(ipeds.complete17f,ipeds.complete18f,ipeds.complete19f,ipeds.complete20f)#2421 observations
#exactly the same with adding all rows
#nrow(ipeds.complete17f)+nrow(ipeds.complete18f)+nrow(ipeds.complete19f)+nrow(ipeds.complete20f)#2421 observations

#rbind is the same with join by all matched cols
#ipeds.complete<-join_all(list(ipeds.complete17f,ipeds.complete18f,ipeds.complete19f,ipeds.complete20f),type="full",match="first")#2420 observations; closest to rbind

#by=PCID limit to merge (turn into one) if find PCID in other dataset; match=first, only takes care of first match
#ipeds.complete<-join_all(list(ipeds.complete17f,ipeds.complete18f,ipeds.complete19f,ipeds.complete20f),by="PCID",type="full",match="first")#2368 observations
#by=PCID limit to (turn into one) if find PCID in other dataset; match = all merge create a copy for all match
#ipeds.complete<-join_all(list(ipeds.complete17f,ipeds.complete18f,ipeds.complete19f,ipeds.complete20f),by="PCID",type="full",match="all")#2379 observations
```


```{r archive cleaning codes}
#################################################################
######################archive codes for cleaning "degree" values###################
#################################################################
#check conc (invalid code in degree)
#ipeds.complete18f%>%group_by(degree)%>%count()#here is where conc exists
#list all curriculum under conc
#ipeds.complete18f%>%filter(degree=="CONC")%>%group_by(curriculum)%>%count()

#replace conc with the correct degree by looking the student up in powercampus
##powercampus lookup results show that we need to replace all CONC with MSM expect HSGJ as MSCJ
###replace HSGJ with MSCJ
#ipeds.complete18f[ipeds.complete18f$curriculum=="HSGJ",11]<-"MSCJ"#no headers/var names anymore so must use 11 as index
#check
#ipeds.complete18f%>%filter(degree=="CONC")%>%group_by(curriculum)%>%count()#no more hsgj
###replace all other CONC with MSM
#ipeds.complete18f[ipeds.complete18f$degree=="CONC",11]<-"MSM"
#check
#ipeds.complete18f%>%group_by(degree)%>%count()#no more conc


#check trk (invalid code in degree)
#ipeds.complete18f%>%filter(degree=="TRK")%>%group_by(curriculum)%>%count()
#lookedup in powercampus, replace all INLICM in TRK as MEDMD
#ipeds.complete18f[ipeds.complete18f$curriculum=="INLICM",11]<-"MEDMD"
#check
#ipeds.complete18f%>%filter(degree=="TRK")%>%group_by(curriculum)%>%count()#no more INLICM
#lookedup in powercampus, replace all PRLICM in TRK as MEDMD
#ipeds.complete18f[ipeds.complete18f$curriculum=="PRLICM",11]<-"MEDMD"
#check
#ipeds.complete18f%>%filter(degree=="TRK")%>%group_by(curriculum)%>%count()#no more prlicm
#lookedup in powercampus, replace INLICE as MEDEL
#ipeds.complete18f[ipeds.complete18f$curriculum=="INLICE",11]<-"MEDEL"
#check
#ipeds.complete18f%>%group_by(degree)%>%count()#no more TRK
```


# IPEDS Completions (due 2022 Oct 19)

#complete file: august 21  december 21 may 22 jan 22

```{r load data without NA cols}
###load complete data
rgs.cp<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/Final List of Graduates By Date Range-Including Certs From Registrar.xlsx",skip = 6)%>%#header on row 7
              janitor::remove_empty(c("rows", "cols"))%>%#remove all-NA, inlcuding headers, rows/cols
              rename(ppid=`People Code ID`)

#remove all-NA cols: sum each col's # of NA rows, as long as not all rows are NA then select them 
rgs.cp <- rgs.cp[ , colSums(is.na(rgs.cp)) < nrow(rgs.cp)] # all rows of selected cols
rgs.cp <- rgs.cp%>%select(-...8)#remove another NA col that has one removable character value
rgs.cp <- rgs.cp[1:(nrow(rgs.cp)-2),]#remove the last two rows that are summarative total info and NAs
```


```{r make up missing cip codes}
###missing CIP CODE
cip_major<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/CIP/Major CIP Codes.xlsx")
#explore: lapply(cip_major, unique)
#CIP code as character
cip_major<-cip_major%>%mutate(`CIP Codes`=if_else(#replace numeric CIP code
  `CIP Codes`<10, paste0("0",`CIP Codes`),#add a 0 before any single number (before demical point)
  as.character(`CIP Codes`)))#the rest as is but convert to character

#unique id: cip_major%>%count(`CIP Codes`,Curriculum,Program)%>%View()#uniquely curriculum+program
cip_major.t<-cip_major%>%select(`CIP Codes`,Curriculum,Program)%>%
  mutate(Program=case_when(Program=="Graduate"~"GRAD",Program=="Undergraduate"~"UNDER"),#match rgs.cp
         major.program=paste0(Program, Curriculum))%>%#make unique identifier
  select(-Curriculum,-Program)%>%#remove used vars
  rename(CIPmatched=`CIP Codes`)

#trim whitespace--leading and trailing spaces
cip_major.t$major.program<-trimws(cip_major.t$major.program, which=c("both"))


#prep the rgs.cp file to be merged/vlookup
rgs.cp<-rgs.cp%>%mutate(major.program=paste0(Program,Major))#unique identifier
#trim whitespace--leading and trailing spaces
rgs.cp$major.program<-trimws(rgs.cp$major.program, which=c("both"))


####merge/vlookup cip to rgs.cp
rgs.cp<-plyr::join_all(list(rgs.cp,cip_major.t),type = "left")

#investigate
rgs.cp%>%count(major.program,CIPmatched,`Cip Code`)%>%
  arrange(major.program)%>%View()

#not the same
rgs.cp%>%filter(CIPmatched!=`Cip Code`)%>%count(major.program,CIPmatched,`Cip Code`)%>%arrange(major.program)%>%View()

#still missing: need to cross match: GRADHuman Resources Management is 52.1301 from the rgscp file
rgs.cp%>%filter(is.na(CIPmatched))%>%count(major.program,CIPmatched,`Cip Code`)%>%arrange(major.program)%>%View()


#solve missing/conflict cip
rgs.cp<-rgs.cp%>%mutate(cip=case_when(
major.program=="GRADCommunication"~"09.0100",
major.program=="GRADMarketing"~"52.1401",
major.program=="GRADProject Management"~"52.1301",
major.program=="GRADAthletic Training MSAT"~"51.0913",
major.program=="GRADBusiness Administration 2"~"52.0201",
major.program=="GRADCreative Writing GR"~"23.1302",
major.program=="GRADHuman Resources Management"~"52.1301",
major.program=="UNDERBusiness Administration"~"52.0201",
major.program=="UNDEREarly Childhood Education"~"13.1210",
major.program=="UNDERElementary Education"~"13.1202",
major.program=="UNDERGlobal Studies"~"30.2001",
major.program=="UNDERHealth Science"~"51.0000",
major.program=="UNDERIDS Forensic Criminology"~"30.9999",
major.program=="UNDERIDS Studio Arts"~"30.9999",
major.program=="UNDERLiberal Arts"~"24.0000",
))%>%
  mutate(cip=if_else(is.na(cip),#recode cip--for cip that haven't been case_when
                        CIPmatched,#assign them the same value with cipmatched
                        cip))%>%#non-na then their own cip
  select(-`Cip Code`,-CIPmatched,-major.program)%>%#used vars for cip
  mutate(cip=if_else(cip=="09.01","09.0100",
                     if_else(cip=="22","22.0000",cip)))%>%unique()#551 rows
```


```{r duplication and SAVE RGS.CP raw}
#duplication: rgs.cp%>%group_by(ppid)%>%count()%>%ungroup()%>%count(n)#due to CIP code
# dup.id<-rgs.cp%>%group_by(ppid)%>%count()%>%ungroup()%>%filter(n>1)
# rgs.cp%>%filter(ppid%in% dup.id$ppid)%>%arrange(ppid)#it's all due to concentration and nothing else

#save
#write_xlsx(rgs.cp,"/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/Final List of Graduates By Date Range-Including Certs From Registrar_clean.xlsx")
```

```{r IPEDS.CP CREATED}
rgs.cp<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/archive/Final List of Graduates By Date Range-Including Certs From Registrar_clean.xlsx")

#select vars needed
ipeds.cp<-rgs.cp%>%select(ppid, Program, Major,cip,Degree,`Graduation Date`)%>%unique()#547 rows
#explore: lapply(ipeds.cp, unique) #no NAs
#investigate duplication: ipeds.cp%>%count(ppid)%>%ungroup()%>%count(n)#all unique
```




```{r ethnicity/gender/age from datamart}
####finding ethnicity/gender for UG 
#UGdatamart to date
dmt0922<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Datamart Files/DataMart To Date/Final Datamart up to Date 09262022.xlsx")
#investigate: lapply(dmt0922[20], unique)

#only vars needed with correct order
dmt0922.s<-dmt0922%>%select(PC_ID, ETHNICITY_REPORT_DESC,GENDER_CODE,BIRTHDATE)%>%
  rename(ppid=PC_ID, ethnicity=ETHNICITY_REPORT_DESC,gender=GENDER_CODE,dob=BIRTHDATE)#consistency when merge

###merge
ipeds.cp<-plyr::join_all(list(ipeds.cp, dmt0922.s),type = "left")%>%unique()#597>574

# duplication: ipeds.cp.t%>%group_by(ppid)%>%count()%>%ungroup()%>%count(n)# have 49 dup
dup.id<-ipeds.cp%>%group_by(ppid)%>%count()%>%ungroup()%>%filter(n>1)
dup<-ipeds.cp%>%filter(ppid %in% dup.id$ppid)#99 rows
#known in the duplicated df
eth.k<-dup%>%filter(ethnicity!="Race and Ethnicity Unknown")%>%unique()%>%#56 rows
  rename(eth.new=ethnicity)%>%#rename as a new var for later merge
  select(ppid,eth.new)
#unknown in the duplicated df
eth.unk<-dup%>%filter(ethnicity=="Race and Ethnicity Unknown")%>%unique()%>%arrange(ppid)#43 rows
#compare
sum(! eth.unk$ppid%in%eth.k$ppid)# all unknown are in known

#reassign those unknown values in the original data
ipeds.cp<-left_join(ipeds.cp, eth.k)%>%#all eth.k's ethnicity as a new col for those eth.k's ppids in origional file
  mutate(eth.new=if_else(is.na(eth.new),#if not settled
                       ethnicity,#equal them to keep their origional ethnicity value
                       eth.new))%>%#if settled, then keep the settled ones
  select(-ethnicity)%>%#used var
  rename(ethnicity=eth.new)%>%#rename to original
  unique()#should reduce 43, 597-554=43 YES! wuwuwu
```




```{r ethnicity/gender from ipeds.enroll}
####### finding ethnicity/gender/age for GD
# check values: ipeds.cp%>%count(ethnicity)#194 GD NA for both gender and ethnicity, 554 rows
#try to found the 194 NA eth values in enrollment data:
enroll2122<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/ipeds_21-22_rerun.xlsx")
# check values: enroll2122%>%count(ethnicity.c) # same value with ipeds.cp, no need to recode
#only vars needed with correct order
enroll2122.s<-enroll2122%>%select(ppid,ethnicity.c,gender.assign)

###merge (new eth col is ethnicity.c)
ipeds.cp<-plyr::join_all(list(ipeds.cp,enroll2122.s),type = "left")%>%#554 rows
  mutate(ethnicity.c=if_else(is.na(ethnicity.c),#if not settled by the new col (from enroll2122.s)
                       ethnicity,#equal them to keep their origional ethnicity value
                       ethnicity.c),#if settled, then keep the settled ones
         gender.assign=if_else(is.na(gender.assign),#if not settled by the new col (from enroll2122.s)
                       gender,#equal them to keep their origional ethnicity value
                       gender.assign),)%>%#if settled, then keep the settled ones
  select(-ethnicity,-gender)%>%#used var
  rename(ethnicity=ethnicity.c, gender=gender.assign)%>%#rename to original
  unique()#547 rows, 29 NAs for both gender and ethnicity

#try to found the rest 29 NAs in 20-21 data
enroll20.21<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2021-2022/Fall Collection/12-month enrollment/FY21 12-month enrollment.xlsx", sheet = "All Students")
#check values: enroll20.21%>%count(`Race/Ethnicity`)
#excel_sheets("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2021-2022/Fall Collection/12-month enrollment/FY21 12-month enrollment.xlsx")
#select vars needed
enroll20.21.s<-enroll20.21%>%select(`People Code Id`,`Race/Ethnicity`, Gender)%>%
  rename(ppid=`People Code Id`,#rename for match when merge
         eth.new=`Race/Ethnicity`)#rename as new col when merge

###merge (new eth col is eth.new)
ipeds.cp<-plyr::join_all(list(ipeds.cp,enroll20.21.s),type = "left")%>%#554 rows
  mutate(eth.new=if_else(is.na(eth.new),#if not settled by the new col (from enroll20.21.s)
                       ethnicity,#equal them to keep their origional ethnicity value
                       eth.new),#if settled, then keep the settled ones
         Gender=if_else(is.na(Gender),#if not settled by the new col (from enroll20.21.s)
                       gender,#equal them to keep their origional ethnicity value
                       Gender))%>%#if settled, then keep the settled ones
  select(-ethnicity,-gender)%>%#used var
  rename(ethnicity=eth.new, gender=Gender)%>%#rename to original
  unique()#547 rows, no ethnicity NAs

#check duplication: ipeds.cp%>%count(ppid)%>%ungroup()%>%count(n) #unique/unduplicated 1 n per ppid
#factorize correct order
ipeds.cp<-ipeds.cp%>% mutate(ethnicity=factor(ethnicity, 
                          levels = c("Non Resident Alien",
                                     "Hispanic",
                                     "American Indian or Alaska Native",
                                     "Asian",
                                     "Black or African American",
                                     "Native Hawaiian or Other Pacific Islander",
                                     "White",
                                     "Two or more Races",
                                     "Race and Ethnicity Unknown")),
                          gender=factor(gender,levels = c("M","F")))
```





```{r age of the rest and SAVE}
#ipeds.cp's age
ipeds.cp<-ipeds.cp%>%mutate(age=age.calc(dob))%>%select(-dob)#remove used
#investigate: ipeds.cp.t%>%filter(is.na(age))%>%count()#194 na values

#########load dataset that contains age data
ug.gd2122<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/ug.gd_21-22_rerun.xlsx")
#select age and ppid
ug.gd2122age<-ug.gd2122%>%select(ppid,age)%>%unique()%>%rename(age.new=age)#always given a new name b/c same name won't merge

#########load dataset that contains age data of the rest from 2020-21 data
cp20.21<-read_excel("/Volumes/lasellshare-1/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2021-2022/Fall Collection/Completions/IPEDS Completions.xlsx",sheet = "Degrees - Registrar")
#excel_sheets("/Volumes/lasellshare-1/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2021-2022/Fall Collection/Completions/IPEDS Completions.xlsx")
#select age and ppid
cp20.21age<-cp20.21%>%rename(ppid=`People Code ID`,age.new=Age)%>%
  select(ppid,age.new)%>%unique()%>%mutate(age.new=age.new+2)#age is taken 2020, now they are 2 years older

#merge 20-21, 21-22 first
age.20_22<-plyr::join_all(list(cp20.21age,ug.gd2122age),type = "full")

#then merge it to ipeds.cp
###merge (new age col is age.new)
ipeds.cp<-plyr::join_all(list(ipeds.cp,ug.gd2122age),type = "left")%>%#554 rows
  mutate(age.new=if_else(is.na(age.new),#if not settled by the new col (from enroll20.21.s)
                       age,#equal them to keep their origional age value
                       as.integer(age.new)))%>%#if settled, then keep the settled ones
  select(-age)%>%#used var
  rename(age=age.new)%>%#rename to original
  unique()#547 rows, 30 age NAs


ipeds.cp<-ipeds.cp%>%mutate(age.cat=case_when(age<=18 ~ "under 18",
                    age>=18 & age<=24 ~ "18-24",
                    age>=25 & age <=39 ~ "25-39", 
                    age>=40 ~"40 and above"),
                  age.cat=factor(age.cat,levels = c("under 18","18-24","25-39","40 and above")))
#check: lapply(ipeds.cp,unique)

#save
#write_xlsx(ipeds.cp,"/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/Complete.with.Ethnicity_age.eric.editted.xlsx")
```

#formal file starts here
```{r reporting!!!!}
ipeds.cp<-read_xlsx("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/Complete.with.Ethnicity_age.eric.editted.xlsx")

ipeds.cp%>%count(age.cat)%>%View()

#see all the cip and degree
ls<-ipeds.cp%>%count(cip,Degree)%>%arrange(cip); View(ls)
#03.0103
ipeds.cp%>%filter(cip=="03.0103")%>%count(ethnicity,gender)%>%View()

#09.0100, BA
ipeds.cp%>%filter(cip=="09.0100",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#09.0100, MSC
ipeds.cp%>%filter(cip=="09.0100",Degree=="MSC")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#09.0199, BA
ipeds.cp%>%filter(cip=="09.0199",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#11.0103
ipeds.cp%>%filter(cip=="11.0103")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#13.0301, BA
ipeds.cp%>%filter(cip=="13.0301",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#13.0301, MEDCLI
ipeds.cp%>%filter(cip=="13.0301",Degree=="MEDCLI")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#13.1099, MEDMD
ipeds.cp%>%filter(cip=="13.1099",Degree=="MEDMD")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#13.1202, BA
ipeds.cp%>%filter(cip=="13.1202",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#13.1202, MEDEL
ipeds.cp%>%filter(cip=="13.1202",Degree=="MEDEL")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#13.1205
ipeds.cp%>%filter(cip=="13.1205")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#13.1210, BA
ipeds.cp%>%filter(cip=="13.1210",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#22.0000, BA
ipeds.cp%>%filter(cip=="22.0000",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#23.0101, BA
ipeds.cp%>%filter(cip=="23.0101",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()

#23.1302, MFA
ipeds.cp%>%filter(cip=="23.1302")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


# 24.0000-AA- treat as reporting to 24.0101
ipeds.cp%>%filter(cip=="24.0000",Degree=="AA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#24.0101, BA, DO NOT HAVE ANY
ipeds.cp%>%filter(cip=="24.0101",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#26.0101, BS
ipeds.cp%>%filter(cip=="26.0101",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()



#30.1901, MSNH
ipeds.cp%>%filter(cip=="30.1901",Degree=="MSNH")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#30.2001, BA
ipeds.cp%>%filter(cip=="30.2001",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()

#30.9999, BA
ipeds.cp%>%filter(cip=="30.9999",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#31.0504, BS
ipeds.cp%>%filter(cip=="31.0504",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#31.0504, MSSM
ipeds.cp%>%filter(cip=="31.0504",Degree=="MSSM")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#31.0505, BS
ipeds.cp%>%filter(cip=="31.0505",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#42.0101, BS
ipeds.cp%>%filter(cip=="42.0101",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#43.0404, BS
ipeds.cp%>%filter(cip=="43.0404",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()



#43.0406, BS
ipeds.cp%>%filter(cip=="43.0406",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#45.0401, BS
ipeds.cp%>%filter(cip=="45.0401",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#45.0401, MSCJ
ipeds.cp%>%filter(cip=="45.0401",Degree=="MSCJ")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#45.1101, BA
ipeds.cp%>%filter(cip=="45.1101",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#50.0407, BA
ipeds.cp%>%filter(cip=="50.0407",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#50.0409, BA
ipeds.cp%>%filter(cip=="50.0409",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#51.0000, BS
ipeds.cp%>%filter(cip=="51.0000",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#51.0913, BS
ipeds.cp%>%filter(cip=="51.0913",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()

#51.0913-MSAT
ipeds.cp%>%filter(cip=="51.0913",Degree=="MSAT")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()



#DID NOT REPORT 51.0913-MSAT!
#51.0913, MSAT
ipeds.cp%>%filter(cip=="51.0913",Degree=="MSAT")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()



#51.2314, MSRS
ipeds.cp%>%filter(cip=="51.2314",Degree=="MSRS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.0201, BS
ipeds.cp%>%filter(cip=="52.0201",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#52.0201, MSRS
ipeds.cp%>%filter(cip=="52.0201",Degree=="MBA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.0211
ipeds.cp%>%filter(cip=="52.0211")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.0301, BS
ipeds.cp%>%filter(cip=="52.0301",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#52.0301-none master
ipeds.cp%>%filter(cip=="52.0301",Program=="GRAD")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.0701, BS
ipeds.cp%>%filter(cip=="52.0701",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.0801, BS
ipeds.cp%>%filter(cip=="52.0801",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#52.0801, SECOND MAJOR- HOW TO REPORT?




#52.0901, BS
ipeds.cp%>%filter(cip=="52.0901",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.0906, BS
ipeds.cp%>%filter(cip=="52.0906",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.0907, BS
ipeds.cp%>%filter(cip=="52.0907",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()



#52.1001, NONE MASTER
ipeds.cp%>%filter(cip=="52.1001")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()



#52.1101, BS
ipeds.cp%>%filter(cip=="52.1101",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.1301, NONE BS
ipeds.cp%>%filter(cip=="52.1301",Program=="UNDER")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#52.1301, 6-CER
ipeds.cp%>%filter(cip=="52.1301",Degree=="CER")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#52.1301, "MSHR","MSM","MSPM"
ipeds.cp%>%filter(cip=="52.1301",Degree%in% c("MSHR","MSM","MSPM"))%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()



#52.1401, BS
ipeds.cp%>%filter(cip=="52.1401",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#52.1401, CER - DID NOT REPORT
ipeds.cp%>%filter(cip=="52.1401",Degree=="CER")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
#52.1401, MSMK
ipeds.cp%>%filter(cip=="52.1401",Degree=="MSMK")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()


#52.1902, BS
ipeds.cp%>%filter(cip=="52.1902",Degree=="BS")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()



#54.0101, BA
ipeds.cp%>%filter(cip=="54.0101",Degree=="BA")%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()
```



```{r second major}
###HOW TO REPORT SECOND MAJOR:
## see if duplication due to two majors: when deciding 1st/ 2nd major -- see all people with 2 majors, arbitrarily select one as 1st and the other as 2nd for all.

#linda sent a updated file containing two double major students: added to ipeds system
ipeds.cp%>%filter(ppid=="P000050884")%>%select(ethnicity,gender)#BS and BA, legal study is the second major
ipeds.cp%>%filter(ppid=="P000051243")%>%select(ethnicity,gender)#BS and BA, legal study is the second major
```



```{r distance education online programs}
#online programs/distance education - 
##For 5Bachelors, most (except completion - see below) are "NONE can be completed entirely via distance education".  
###Bachelors Completion: 1communication, 2psychology, 3muti/inter-disciplinary studies, and 4BA in business administration are "SOME can be completed entirely via distance education".  
###For 7Master's and 6CER, most (expect in Education) are "ALL can be completed entirely via distance education."
```




```{r completer data}
#all completers
ipeds.cp%>%
  group_by(ethnicity,gender,.drop = FALSE)%>%count()%>%
  pivot_wider(names_from = gender,values_from = n)%>%View()

#completers by level
ipeds.cp%>%count(Degree)



##Associate's degree level: gender
ipeds.cp%>%filter(Degree=="AA")%>%
  group_by(gender,.drop = FALSE)%>%count()%>%View()

##Associate's degree level: race
ipeds.cp%>%filter(Degree=="AA")%>%
  group_by(ethnicity,.drop = FALSE)%>%count()%>%View()

##Associate's degree level: age
ipeds.cp%>%filter(Degree=="AA")%>%
  group_by(age.cat,.drop = FALSE)%>%count()%>%View()



##Bachelor's degree level: gender
ipeds.cp%>%filter(Degree%in%c("BS","BA"))%>%
  group_by(gender,.drop = FALSE)%>%count()%>%View()

##Bachelor's degree level: race
ipeds.cp%>%filter(Degree%in%c("BS","BA"))%>%
  group_by(ethnicity,.drop = FALSE)%>%count()%>%View()

##Bachelor's degree level: age
ipeds.cp%>%filter(Degree%in%c("BS","BA"))%>%
  group_by(age.cat,.drop = FALSE)%>%count()%>%View()



##Master's degree level: gender
ipeds.cp%>%filter(Program=="GRAD",Degree!="CER")%>%
  group_by(gender,.drop = FALSE)%>%count()%>%View()

##Master's degree level: race
ipeds.cp%>%filter(Program=="GRAD",Degree!="CER")%>%
  group_by(ethnicity,.drop = FALSE)%>%count()%>%View()

##Master's degree level: age
ipeds.cp%>%filter(Program=="GRAD",Degree!="CER")%>%
  group_by(age.cat,.drop = FALSE)%>%count()%>%View()




##Postbaccalaureate and post-master's certificates degree level: gender
ipeds.cp%>%filter(Degree=="CER")%>%
  group_by(gender,.drop = FALSE)%>%count()%>%View()

##Postbaccalaureate and post-master's certificates degree level: race
ipeds.cp%>%filter(Degree=="CER")%>%
  group_by(ethnicity,.drop = FALSE)%>%count()%>%View()

##Postbaccalaureate and post-master's certificates degree level: age
ipeds.cp%>%filter(Degree=="CER")%>%
  group_by(age.cat,.drop = FALSE)%>%count()%>%View()



#NOTE: 
#5 bachlor, 6 means CER, 7 means master
#master degree == grad but not cer 
##aa is coded as under; cer can be under and grad
##bs in cs and bs in eng = one degree award
##bs in cs and mba = two degree award
##
##refer to enrollment report for the gender unknown
```



```{r other cip codes screen}
#09.0199, BA
ipeds.cp%>%filter(cip=="09.0199",Degree=="BA")%>%
  group_by(Major)%>%count()%>%View()


#13.1099, MEDMD
ipeds.cp%>%filter(cip=="13.1099",Degree=="MEDMD")%>%
  group_by(Major)%>%count()%>%View()


#30.9999, BA
ipeds.cp%>%filter(cip=="30.9999",Degree=="BA")%>%
  group_by(Major)%>%count()%>%View()
```


```{r}
ipeds.cp%>%filter(ethnicity=="American Indian or Alaska Native")


```






