---
title: "ranking-specific"
author: "Linli Zhou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Course data for Princeton Review
```{r princeton review}
#external reporting for the Princeton Review 2022-8-19 due

#Read local data files for course 2021-2022
course21_22<-read.csv("/Users/linlizhou/Documents/LASELL/working on/Student Info by Course and Fiscal Year.csv")%>%unique()
#course enrollment data for fall/spring/summer main, session1, and 2
#run from report manager: https://reports.lasell.edu/Reports/report/IR/Student%20Info%20by%20Course%20and%20Fiscal%20Year


#1.goal -question 10 and 11: confirm the following are offered as undergraduate course
dplyr::glimpse(course21_22)
c("Entrepreneurial Leadership","Entrepreneurial Management","Introduction to Entrepreneurship","Introduction to New Business Ventures","New Product Development","New Venture Management","Venture Capital & Private Equity") %in% course21_22$Course_Name
#cannot find exact match except "New Product Development"


#filter business and management school and see the courses offered there
library(dplyr)
#investigate department names
course21_22 %>% dplyr::group_by(Course_Department) %>% count()
#list business school courses
course21_22%>%filter(Course_Department=="BUSS")%>%group_by(Course_Name)%>%count()
#find two courses that contains Entrepreneur: "Amer Entrepreneurs: Trends & Innovation" and "Special Topics in Entrepreneurship"
#then, need to confirm with Bruce for question 10 and 11


#let's investigate which courses does Bruce teach, since Bruce is the only faculty for the entreprenurship program
glimpse(course21_22)
course21_22 %>% filter(Course_Department=="BUSS")%>%
  group_by(Instructors)%>%count() #find out McKinnon, Bruce

course21_22%>% filter(Instructors=="McKinnon, Bruce" & Course_Department=="BUSS") %>%group_by(Course_Name) %>% count() #there are 7 courses
#asked Eric, "Amer Entrepreneurs: Trends & Innovation","Entrepreneurship & Venture Creation", "Managing the Growing Company" and "Special Topics in Entrepreneurship" are the four courese entrepreneurship-related.





#2.goal-question 15: What was the total enrollment (full-time and part-time) in your undergraduate entrepreneurship offerings for the 2021-2022 academic year?

#based on the 4 courses are related with entrepreneurship, I can count the enrollment based on the n in the following formula
t3<-course21_22%>%filter(
  Course_Name %in% c("Amer Entrepreneurs: Trends & Innovation", "Entrepreneurship & Venture Creation", "Managing the Growing Company", "Special Topics in Entrepreneurship") 
) %>% group_by(Course_Name) %>% summarise(course_appearance=n())

sum(t3$course_appearance)#61 students



#goal-question 15a: within those students who enrolled in the entrepreneurship-related course, count their unique majors
glimpse(course21_22)
course21_22%>%filter(
  Course_Name %in% c("Amer Entrepreneurs: Trends & Innovation", "Entrepreneurship & Venture Creation", "Managing the Growing Company", "Special Topics in Entrepreneurship") 
) %>% group_by(Major) %>% summarise(major_appearance=n())#14 majors
```


#Web Scrap Course for US News

```{r US News web scrapping courses}
# US NEWS ONLINE PROGRAM 07/01/2021-06/30-2022, due 2022-10-15
#COURSE QUESTIONS

#question: Amount of curriculum for undergrad completion/online program
library(rvest)
#read html and parse it into R readable contents
pg<-read_html("https://www.lasell.edu/graduate-studies/academics/bsba.html#Curriculum-Section")
#look at it (a list object that contains the tree-like structure)
pg
#search using nodes (html tags or css class) and print text
#pg %>% html_nodes("body")%>%html_text()#indeed all contents of body
#search using css class as nodes
my.title<-pg %>% html_nodes(".code")%>%html_text() 
  my.title%>%length()#we must add a . before the class name
  
#save to df
my.df<-data.frame(BSBA=my.title)



##############web2
pg.2<-read_html("https://www.lasell.edu/graduate-studies/academics/psychology.html#Curriculum-Section")
#make a list of course titles
my.title2<-c()#initialize a empty list
for (i in 1:30 )  { #estimate 30 i
  my.title2[[i]]<-#have to use [[]] to indicate the list index
    pg.2%>%html_nodes(
      xpath=paste0("/html/body/div[1]/main/div/div[1]/div[2]/div[2]/table/tbody/tr[",i,"]/td[1]"#paste the xpath using i
      )) %>% html_text()# print out corresponding text to nodes
  i<-i+1 #add one to go to next index
}

library(stringr)
#remove empty and not in format of -- using any capital letters follow by any number
my.title2<-my.title2[str_detect(my.title2,"[A-Z][0-9]")]
my.title2%>%length()

#save to df
length(my.title2)=length(my.title)
my.df<-my.df%>%mutate(Psych=my.title2)

##############web3
pg.3<-read_html("https://www.lasell.edu/graduate-studies/academics/communication.html")
#make a list of course titles
my.title3<-c()#initialize a empty list
for (i in 1:30 )  { #estimate 30 i
  my.title3[[i]]<-#have to use [[]] to indicate the list index
    pg.3%>%html_nodes(
      xpath=paste0("/html/body/div[1]/main/div/div[1]/div[2]/div[2]/table/tbody/tr[",i,"]/td[1]"#paste the xpath using i
      )) %>% html_text()# print out corresponding text to nodes
  i<-i+1 #add one to go to next index
}

library(stringr)
#remove empty and not in format of -- using any capital letters follow by any number
my.title3<-my.title3[str_detect(my.title3,"[A-Z][0-9]")]
my.title3%>%length()


#save to df
length(my.title3)=length(my.title)
my.df<-my.df%>%mutate(Com=my.title3)
```



# !!A VLOOKUP Approach to US News!!

```{r list of targeted students and SAVE}
#US NEWS ONLINE PROGRAM 07/01/2021-06/30-2022, due 2022-10-15
#load merged backup data (in enrollment ipeds folder)
ug.gd<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/merged enrolldata/ug.gd_21-22_rerun.xlsx")

#create USNEWS online program dataset: filter program names
stu.ls<-ug.gd%>%
  filter(Program %in% c("MSCJ","MSM","MBA",#master online programs
                        "Business Administration",#bachelor BussAdmin
                        "Communication Bachelors Completion",#bachelor completion programs
                        "Interdisciplinary Bachelors Completion","Psychology Bachelors Completion"))%>%
  #set up the right order of programs
  mutate(Program=factor(Program,levels = c("Business Administration",#correct ordering
                                           "Communication Bachelors Completion",
                                           "Interdisciplinary Bachelors Completion",
                                           "Psychology Bachelors Completion",
                                           "MSCJ","MSM","MBA")))%>%
  select(ppid,Name,Program)%>%unique()

##investigate duplicated ppid: due to names
dup.id<-stu.ls%>%group_by(ppid)%>%count()%>%ungroup()%>%filter(n>1);  stu.ls%>%filter(ppid%in% dup.id$ppid)%>%arrange(ppid)

#remove duplication: powercampus results
stu.ls<-stu.ls%>%filter( ! (ppid=="P000008261"&Program=="MSM"))
#check: stu.ls%>%filter(ppid=="P000008261") # kept MBA

#save for admission/fin-aid office
write_xlsx(stu.ls,"/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/US News/2022 fall/OnlineStudentsList.xlsx")
```

#create usn.enroll: merging student list & enrollment vars
```{r select enrollment-vars and deduplicate}
#select var from enrollment data
usn.enroll<-ug.gd%>%select(ppid,`gov id`,`Birth Date`,ethnicity.c,Gender,
         level,transfer,NewRet,status,`Cum Credits`)%>%unique()#779 rows
#merge to the list of students
usn.enroll<-left_join(stu.ls,usn.enroll)

##investigate duplicated ppid: due to cum credits
dup.id<-usn.enroll%>%group_by(ppid)%>%count()%>%ungroup()%>%filter(n>1);  usn.enroll%>%filter(ppid%in% dup.id$ppid)%>%arrange(ppid)
#de-duplication: first replace NA
usn.enroll$`Cum Credits`[is.na(usn.enroll$`Cum Credits`)]<-0#replace NA value with zero
#then keep only the top for each ppid after descending cum credit: using distinct ppid
usn.enroll<-usn.enroll%>%#aim: assign one value for duplicated id (to resolve conflict)    
  arrange(desc(`Cum Credits`))%>%#largest cumcredit at the top (with no NA, if have NA, NA will be at top)
  arrange(ppid)%>%#same id group and has large-low cumcredit
  distinct(ppid,.keep_all = TRUE)#distinct will keep the !first row! (the correct cum credit), 316 rows
```


```{r all enrollment-vars and SAVE}
###########add needed cols based on enroll vars
#define function
age.calc <- function(dob, age.day = "2021-07-01", units = "years", floor = TRUE) {
  calc.age = interval(dob, age.day) / duration(num = 1, units = units)
  if (floor) return(as.integer(floor(calc.age))) #floor=round down to the nearest interger
  return(calc.age)}#return has to be its own row
#calculate age
usn.enroll<-usn.enroll%>%mutate(
  age= age.calc(`Birth Date`),
  age.cat=case_when(age<=22 ~ "22 or younger",
                    age>=23 & age<=29 ~ "23-29",
                    age>=30 & age <=39 ~ "30-39", 
                    age>=40 & age <=49 ~ "40-49",
                    age>=50 & age <=59 ~ "50-59",
                    age>-60 ~"60 or older"),
  age.cat=factor(age.cat),
#calculate progress based on cum credits
  CreditPrt=`Cum Credits`/120,#total is 120 credits for most programs NEEDS TO CONFIRM WITH ERIC
  CreditPrt=case_when(CreditPrt<.25~"<25%",
                      CreditPrt>=.25 & CreditPrt<.50~"25-49%",
                      CreditPrt>=.50 & CreditPrt<=.74~"50-74%",
                      CreditPrt>.75~">75%"),
  CreditPrt=factor(CreditPrt,levels = c("<25%","25-49%","50-74%",">75%")))%>%
  select(-`Birth Date`)#remove used vars

#save for admission/fin-aid office
write_xlsx(usn.enroll,"/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/US News/2022 fall/OnlineStudentEnroll.xlsx")
```

```{r enrollment questions}
usn.enroll<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/US News/2022 fall/OnlineStudentEnroll.xlsx")#indeed we saved it there for jennifer with that file name
#answering questions:
#age/birth date of UG, question 70##
#calculate age from birth date
usn.enroll%>%filter(Level=="UG")%>%group_by(age.cat)%>%count()%>%
  View()#for copy and paste convenience


#UG age question 
usn.enroll%>%filter(Level=="UG",`New Ret Term YN`=="new")%>%
  summarise(mean.age=round(mean(age,na.rm = TRUE),digits=0))%>%#auto remove NA
  View()#for copy and paste convenience


#GD age question 49 or 52###
usn.enroll%>%filter(Level=="GD")%>%group_by(Program)%>%
  summarise(mean.age=round(mean(age,na.rm = TRUE),digits=0))%>%#auto remove NA
  View()#for copy and paste convenience



#international students of UG, question 53,54##
usn.enroll%>%filter(Level=="UG")%>%group_by(ethnicity.c)%>%#UG's ethnicity
  summarise(cnt=n())%>%mutate(prt=formattable::percent(cnt/sum(cnt),digits = 0))%>%#count and percentage
  filter(ethnicity.c=="Non Resident Alien")%>%#question only asked international students
  View()#for copy and paste convenience

#non-transfer of UG, question 55##
usn.enroll%>%filter(Level=="UG")%>%group_by(transfer,NewRet,status)%>%count()%>%
  filter(NewRet=="new",#first year freshmen
         status=="FT")%>%#full time
         #all program are degree awarding programs
  View()


#total of UG, question 55##
usn.enroll%>%filter(Level=="UG")%>%summarise(totUG=n())%>%View()
#total UG by gender
usn.enroll%>%filter(Level=="UG")%>%count(Gender)%>%View()
#total UG by ethnicity
usn.enroll%>%filter(Level=="UG")%>%count(Ethnicity)%>%View()
usn.enroll%>%filter(Ethnicity=="Non Resident Alien",Level=="UG")%>%select(`People Code Id`)
usn.enroll%>%count(Ethnicity)
#new UG by ethnicity
usn.enroll%>%filter(Level=="UG",`New Ret Term YN`=="new")%>%count(Ethnicity)%>%View()


#total GD by ethnicity
usn.enroll%>%filter(Program=="MSM")%>%count(Ethnicity)%>%View()
usn.enroll%>%filter(Program=="MBA")%>%count(Ethnicity)%>%View()
usn.enroll%>%count(Program)


#cum credit progress out of 120 credits of UG, question 57##
usn.enroll%>%filter(Level=="UG")%>%group_by(CreditPrt)%>%count()%>%View()


#GD gender question 47 or 50###
usn.enroll%>%filter(Level=="GD")%>%group_by(Program,Gender)%>%count()%>%arrange(Program)%>%
  pivot_wider(names_from = Gender,values_from = n)%>%View()
```


# Course data for US News
```{r no-option course data and course list}
#reload stu.ls (all online program students)
stu.ls<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/US News/2022 fall/OnlineStudentsList.xlsx")
#load crs data
noopt<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/merged course data/NO-Option_Course21-22.xlsx")
#initiate needed vars 
usn.crs<-noopt%>%select(ppid,course)%>%
  filter(str_detect(course, "^BUSS|^CJ|^COM"))#need to make sure course is opened by their program
#check: usn.crs%>%count(course)
#create merged usn.crs
usn.crs<-left_join(stu.ls,usn.crs)
#unique course names
##create course code (capitalized letters)
usn.crs<-usn.crs%>%mutate(CourseCode=str_extract(course, "[A-Z]+[0-9]+\\.[A-Z]"),
                          Department=str_extract(course, "[A-Z]+"))%>%#extract any number of capitalized letter, then followed by any number of numbers, then followed by a period (\\.), then one capital letter
  select(-course)#remove used

#duplicated
usn.crs%>%count(ppid,CourseCode)%>%ungroup()%>%count()#unique by ppid and coursecode, pp are taking muti-course but after consideirng course, they are unique (no other var has conflict)

#create course list that students online are taking
crs.ls<-usn.crs%>%select(-ppid, -Name)%>%unique()#69 sections
```


```{r sectiontally course size data for course list and SAVE}
#load section tally class size data
sec<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/merged course data/sectionInfo.xlsx")
#initiate needed vars
sec.s<-sec%>%select(event_id,section,Current_Enrollment,course_start_date)%>%#need course start date for the same course offered at different terms/times
  mutate(CourseCode=paste(sep=".",event_id,section))%>%#same format
  select(-event_id,-section)%>%unique()%>%
  filter(Current_Enrollment>1)#remove 0 and 1 (and na) coureses independent study courses
#duplicated: none
sec.s%>%group_by(CourseCode,course_start_date)%>%summarise(cnt=n())%>%ungroup()%>%count(cnt)#each course appeared muti-times



#create merged usn.crs: only keep size info for online students' courses
crs.sec<-left_join(crs.ls,sec.s)%>%
  mutate(size=case_when(Current_Enrollment==1~"1",
                        Current_Enrollment>=2 & Current_Enrollment<=9~"2-9",
                        Current_Enrollment>=10 & Current_Enrollment<=19~"10-19",
                        Current_Enrollment>=20 & Current_Enrollment<=29~"20-29",
                        Current_Enrollment>=30 & Current_Enrollment<=39~"30-39",
                        Current_Enrollment>=40~">40"),
         size=factor(size, levels=c("1","2-9","10-19","20-29","30-39",">40")))%>%
  filter(!is.na(Current_Enrollment))#remove NA caused by not finding enrollment size

#save
openxlsx::write.xlsx(list('courselist' = crs.ls, 'coursesize' = crs.sec), file = "/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/US News/2022 fall/OnlineStudentCourse.Class.xlsx") 
```


```{r report course.class}
#question: for each program, number of class (section) in range of different class size
crs.sec%>%count(Department,CourseCode,course_start_date,size)%>%arrange(Department)%>%
  group_by(Department,size)%>%summarize(size.n=sum(n))

#question: for each program, mean class size
crs.sec%>%group_by(Department)%>%summarise(mn.size=mean(Current_Enrollment))

#instructor FT.PT status, race, degreeobtained
```



# UG Retention
```{r}
#UG students who enrolled in 2020-2021
excel_sheets("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2021-2022/Fall Collection/12-month enrollment/FY21 12-month enrollment.xlsx")
ug.retain21<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2021-2022/Fall Collection/12-month enrollment/FY21 12-month enrollment.xlsx",sheet = "Unduplicated UG")
#UG bachelor completion (BussAdmin only) students
stu21<-ug.retain21%>%filter(Curriculum%in%c("Business Administration"))#8 students

#UG students who enrolled in 2021-2022
ug.retain22<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/crs.ipeds.matched_21-22_rerun.xlsx")

#whether 21student are in 22enrolled: retention is how many student is there in 22 data
stu21$`People Code Id`%in%ug.retain22$ppid %>%sum() #7 out ot 8 retained: 87.5%
```


# GD Retention data
```{r US News entered last year return and graduated}
#load and clean data 
retention<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Data and Analyses/Graduate Retention/2009 Fall - Present Graduate Retention.xlsx")%>%rename(ppid=`People Code Id`)
85
#replace NA with "n
retention<-retention%>%mutate_at(c(grep("Fall$|Spring$|^Grad AY",names(retention),value = TRUE)),#all relevant cols
                               ~replace_na(.,"n"))%>%#replace their NA with "n
#pattern for enter term: concatenate recent terms
retention<-retention%>%unite("RecentTermPattern",`2020 Fall`:`2021 Fall`,remove = FALSE,sep = "")




#QUESTION GD138/141: "First enrolled between July 1, 2020 and June 30, 2021, re-enrolled or graduated anytime within the next 12 months?"--student count and prt




#re-enrollment students !who first entered July 1, 2020 and June 30, 2021!
reenroll<-retention%>%filter(Degree%in%c("MSCJ","MSM","MBA"),#Master online programs
                   `Entering Semester`%in%c("2020 Fall","2021 Spring"))%>% #begins 2020 fall or 2021 spring
            filter(!RecentTermPattern %in% c("Ynn",#not those who enrolled for the first and no show for the rest
                                            "nYn"))%>%##not those who enrolled for the first and no show for the rest
            group_by(ppid,Degree)%>%summarise(reenroll=n())

#graduated students !who first entered July 1, 2020 and June 30, 2021!
graduated<-retention%>%filter(Degree%in%c("MSCJ","MSM","MBA"),#Master online programs
                   `Entering Semester`%in%c("2020 Fall","2021 Spring"))%>% #begins 2020 fall or 2021 spring
            filter(`Grad Date`>"2020-07-01"&`Grad Date`<"2022-06-30")%>%
            group_by(ppid,Degree)%>%summarise(graduated=n())

#merge: unduplicated return and grad students
ret.grad<-plyr::join_all(list(reenroll,graduated),type = "full")%>%
                select(ppid,Degree)%>%#one appearance is one, then no need the cnt vars
                unique()%>%arrange(ppid)%>%group_by(Degree)%>%summarise(ret.grad=n())

#total: first time students
tot.firsttime<-retention%>%filter(Degree%in%c("MSCJ","MSM","MBA"),#Master online programs
                   `Entering Semester`%in%c("2020 Fall","2021 Spring"))%>%
                group_by(Degree)%>%summarise(tot.firsttime=n())

#calculate: the prt of return/grad students among all first time students (enrolled in 2020F/2021S)
plyr::join_all(list(ret.grad,tot.firsttime),type = "full")%>%
  mutate(prt=formattable::percent(ret.grad/tot.firsttime,digits = 0))%>%
  View()
```




# Completion data
```{r US News all graduated}
#QUESTION UG35/128&GD136/139: Report the count of students who graduated from your institution’s  program between July 1, 2021 and June 30, 2022.----do not use CIP because they overlapp with on-campus programs---use degree and major instead
#load data
rgs.cp<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/Final List of Graduates By Date Range-Including Certs From Registrar_clean.xlsx")

## UG graduated 21-22 in online bachelor programs
rgs.cp%>%filter(Program=="UNDER",#online bachelor programs
                Major%in%c("Business Administration",
                           grep(value=TRUE,"Completion",rgs.cp$Major)))%>%
        count(Major)%>%View()

#MSCJ, MSM, MBA graduated 21-22 
rgs.cp%>%filter(Degree%in% c("MSCJ", "MSM", "MBA"))%>%count(Degree)%>%View()
```


#Veteran data
```{r US News}
#US NEWS ONLINE PROGRAM 07/01/2021-06/30-2022, due 2022-10-15
#VETERAN QUESTIONS

usn.vet<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/US News/Online Bachelor's/2022/Veteran Student Benefits 2021-22.xlsx")

usn.vet<-usn.vet%>%mutate(prg.cur=paste0(program,Curriculum))
ls1<-usn.vet%>%count(prg.cur); View(ls1)
usn.vet%>%filter(prg.cur=="UNDERBusiness Administration")%>%group_by(program)%>%count()#Bachelor completion
usn.vet%>%filter(prg.cur=="GRADCriminal Justice")%>%group_by(program)%>%count()#MSCJ
usn.vet%>%filter(prg.cur%in% c("GRADEmergency & Crisis Management",#Hospitality & Event Management (MSM)
                               "GRADHuman Resources Management",#Human Resources (MSHR)
                               "GRADManagement",#Management (MSM)
                               "GRADMarketing",#Marketing (MSMK)
                               "GRADProject Management",#Project Management (MSPM)
                               "GRADSport Management"
                               ))%>%group_by(prg.cur)%>%count()#MSM
usn.vet%>%filter(prg.cur=="GRADBusiness Administration")%>%group_by(program)%>%count()#MBA

ls<-usn.vet%>%group_by(Curriculum)%>%count(); View(ls)
##search for business administration
#usn.vet%>%filter(grepl("[Bb][Uu]",usn.vet$Curriculum))%>%group_by(Curriculum)%>%count()#see "Business Administration"
##search for completion programs
#usn.vet%>%filter(grepl("[Cc]omp",usn.vet$Curriculum))%>%group_by(Curriculum)%>%count()#non
```


```{r look at different datasets}
library(readxl)
cp<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/Completions/Complete.with.Ethnicity_age.eric.editted.xlsx")
enroll<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/merged enrolldata/ug.gd_21-22_rerun.xlsx")
crs<-read_csv("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/merged course data/Student Info by Course and Fiscal Year.csv")
sec<-read_excel("/Volumes/lasellshare/Faculty_Staff_Shares$/IR/Surveys/IPEDS/2022-2023/Fall Collection/12-month enrollment/merged course data/sectionInfo.xlsx")

sec%>%count(Course_type)
noopt%>%count(event_type)
sec%>%count(section)
names(noopt)
```

